version:  "3.8"

networks:
  backend:
    external: false
    name: backend
services:
  getirdb:
    networks:
      - backend
    image: mongo:latest
    container_name: getirdb
    ports:
      - 27017:27017
  app-image:
    networks:
      - backend
    image: app-image
    container_name: readingisgood
    ports:
      - 8080:8080
    links:
      - getirdb